openapi: 3.0.1
info:
  title: His
  description: API Definition of His
  version: 1.0.0
servers:
- url: http://localhost:8290/his
paths:
  /:
    get:
      responses:
        default:
          description: Default response
